import os
import json
import re
from datetime import datetime
import pandas as pd
import requests

from core.logging_utils import push_log
from core.io_utils import ensure_dir

DESCRIPTION = "Step 3: Education Extractor. Reads an Excel file with raw OCR text, uses Ollama to extract education details, and outputs the final dataset."
BADGES = ["Ollama", "Education Data", "Regex Salvage"]
ASSISTANT_HINT = "Upload the Excel file generated by the Batch OCR Engine and select the column containing the OCR text."
SUPPORTS_LOCAL_PATHS = False

PARAMS = [
    {"name": "input_file", "type": "file", "label": "Upload OCR Excel File"},
    {"name": "text_column", "type": "column", "label": "Column containing OCR Text", "source": "input_file"},
    {"name": "ollama_url", "type": "text", "label": "Ollama URL", "default": "http://localhost:11434"},
    {"name": "ollama_model", "type": "text", "label": "Ollama Model", "default": "llama3.1"},
]

def _read_table(fp: str) -> pd.DataFrame:
    if fp.lower().endswith(".csv"):
        return pd.read_csv(fp)
    return pd.read_excel(fp)

def _salvage_broken_json(text: str) -> dict:
    salvaged = {}
    
    # Pattern 1: Hunt for broken JSON format
    json_pattern = re.compile(r'"([a-zA-Z0-9_]+)"\s*:\s*(?:"([^"]*)"|([^,}\n]+))')
    for match in json_pattern.finditer(text):
        if match.group(2) is not None:
            salvaged[match.group(1)] = match.group(2).strip()
        elif match.group(3) is not None:
            salvaged[match.group(1)] = match.group(3).strip(' \r\n,"')
            
    if salvaged: 
        return salvaged

    # Pattern 2: Hunt for Markdown list format
    md_pattern = re.compile(r'[*+-]?\s*[`*]*([a-zA-Z0-9_]+)[`*]*\s*:\s*([^\n]+)')
    for match in md_pattern.finditer(text):
        key, val = match.group(1), match.group(2).strip(' \r\n,"\'')
        if len(key) < 50: 
            salvaged[key] = val
            
    return salvaged

def _extract_clean_json(text: str) -> str:
    text = str(text).strip()
    start_dict = text.find('{')
    if start_dict != -1:
        end_dict = text.rfind('}')
        if end_dict != -1:
            return text[start_dict:end_dict+1]
    return ""

def _ask_ollama(ollama_url: str, model: str, text: str) -> dict:
    prompt = f"""
You are an expert document extraction engine. Extract education details from the OCR text into STRICT JSON.
Keys required: "candidate_name", "institution_name", "degree", "course", "roll_number", "registration_number", "passing_year", "marks_or_cgpa", "document_type", "remarks".
If a field is missing, leave it as an empty string "".

OCR TEXT:
\"\"\"{text[:10000]}\"\"\"
"""
    payload = {"model": model, "prompt": prompt, "stream": False, "options": {"temperature": 0.0}}
    response = requests.post(ollama_url.rstrip("/") + "/api/generate", json=payload, timeout=180)
    response.raise_for_status()
    raw_response = response.json().get("response", "")
    
    clean_json = _extract_clean_json(raw_response)
    if clean_json:
        try:
            return json.loads(clean_json)
        except:
            pass
    return _salvage_broken_json(raw_response)

def run(inputpath, outputpath, kwargs, log_queue=None):
    log_queue = log_queue or []
    ensure_dir(outputpath)
    
    file_path = kwargs.get("input_file")
    text_column = kwargs.get("text_column", "").strip()
    ollama_url = kwargs.get("ollama_url")
    ollama_model = kwargs.get("ollama_model")
    
    if not file_path or not text_column:
        raise ValueError("Please provide an input file and select the text column.")
        
    df = _read_table(file_path).fillna("")
    total = len(df)
    
    all_rows = []
    
    for idx, row in df.iterrows():
        orig_data = row.to_dict()
        text_to_process = str(orig_data.get(text_column, "")).strip()
        
        push_log(log_queue, "INFO", f"[{idx+1}/{total}] Extracting education data via Ollama...")
        
        if len(text_to_process) < 50:
            orig_data["LLM_Status"] = "Skipped - Text too short"
            all_rows.append(orig_data)
            continue
            
        try:
            extracted_dict = _ask_ollama(ollama_url, ollama_model, text_to_process)
            merged_row = {**orig_data, **extracted_dict}
            merged_row["LLM_Status"] = "Success"
            all_rows.append(merged_row)
        except Exception as e:
            push_log(log_queue, "ERROR", f"[{idx+1}/{total}] LLM extraction failed: {e}")
            orig_data["LLM_Status"] = f"Failed: {e}"
            all_rows.append(orig_data)

    final_df = pd.DataFrame(all_rows)
    
    # Ensure Original columns are first
    orig_cols = list(df.columns)
    new_cols = [c for c in final_df.columns if c not in orig_cols]
    final_df = final_df[orig_cols + new_cols]
    
    out_name = f"LLM_Extracted_Education_Data_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
    out_path = os.path.join(outputpath, out_name)
    
    final_df.to_excel(out_path, index=False)
    push_log(log_queue, "SUCCESS", "Education LLM Extraction complete!")
    
    return {"output_files": [out_path]}